spring.application.name=Restaurant-website

spring.datasource.url=jdbc:mysql://localhost:3306/restaurant
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
jwt.secret=QeUaw33/mnlqW4CFrYdcH6vsqKvgBVNoOCzg5VnnpZjWOD/7DtzvL9wjtRFXl/jrH+a5qB49nmA/lgZWbVl4ag==
jwt.expiration=86400000

cloudinary.cloud_name=drixmxite
cloudinary.api_key=856168741242374
cloudinary.api_secret=LBdNyt_pZjuao0Z_F_pLUEv1JyA

telegram.bot.username=Delivia_bot
telegram.bot.token=7790694149:AAHvITzOkKADSZhyNRqRiWAxOTvagToaJPQ
restaurant.api.url=http://localhost:8080/api/menu

logging.level.org.example.restaurantwebsite=DEBUG
logging.level.org.springframework.web=INFO


//eisuPl+PoXUgT20d4sR3rw==EMRv5XGYaiA3wAlu
